---
title: "Class08"
date: "2026-09-23"
output:   
  html_document:
  toc: true
  toc_float: true
  number_secitons: true
  code_download: true
  code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cincy Crashes

```{r APIs}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON()
```


# FRED API
```{r FRED}
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string()|>
  jsonlite::fromJSON() -> ohio_jobs


jobs_df = ohio_jobs[[13]]

# To get data from sept 1, 2026

# (a) Get all the data filter rows I want 
dplyr::glimpse(jobs_df)
jobs_df |> 
  dplyr::mutate(
    date = lubridate::ymd(date)
  ) |> 
  dplyr::filter(date >= '2026-09-01') -> jobs_df_mod

# (b) Or use API

httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start="2026-09-01"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string()|>
  jsonlite::fromJSON() -> ohio_jobs_sep_2026

ohio_jobs_sep_2026_df = ohio_jobs_sep_2026$observations
```

# USA JOBS API
```{r usajobs}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "rosbotgm@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_list

usa_df = usa_jobs_list$SearchResult$SearchResultItems

jobs_small = usa_df |>
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department = MatchedObjectDescriptor.DepartmentName,
    agency = MatchedObjectDescriptor.OrganizationName,
    location = MatchedObjectDescriptor.PositionLocationDisplay,
    closes = MatchedObjectDescriptor.ApplicationCloseDate
  )

#1. How many federal postings match "Data Analyst" today?

usa_jobs_list$SearchResult$SearchResultCountAll

#2. Which three departments have the most of them?
usa_df |>
  dplyr::count(MatchedObjectDescriptor.DepartmentName, sort = TRUE) |>
  head(3)


index_data_analyst = jobs_small$title |>
  stringr::str_detect(pattern = "Data Analyst|Data Analytics")

jobs = jobs_small[index_data_analyst, ]  
```

